try {
    $x =1;
}catch  (\Exception $e) {
    throw $e
}
